apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-init
  namespace: servicedeployed
spec:
  interval: 60m0s
  sourceRef:
    kind: GitRepository
    name: cluster-init
    namespace: servicedeployed
  path: .
  prune: true