apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-kubevirt-operator
  namespace: kubevirt
spec:
  interval: 60m0s
  sourceRef:
    kind: GitRepository
    name: flux-sync
  path: ./infrastructure/kubevirt/core/operators
  prune: true