apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-kubevirt
  namespace: flux-system
spec:
  interval: 60m0s
  sourceRef:
    kind: GitRepository
    name: flux-sync # helm chart name for flux-sync
  path: ./infrastructure/kubevirt/latest
  prune: true